### ISSUE TITLE
Using OnionGpio w/DHT22 temp/humidity sensor

### ISSUE THREAD

**Issue by bhontz** [OnionIoT/onion-gpio-sysfs#2]
Have you had any experience using this module with a DHT22 sensor?  I've been following pigpio and Adreno C examples and I only seem to be able to recognize the pin going high, but not a change in the pin state.   I'll keep plugging, but thought it worth asking if you'd seen fit to experiment along these lines.  Thanks in advance, and thanks^2 for the effort behind this repository and for sharing!

**Comment by pavelmetrokhin** [comment]
Hi Bhontz, 
Please check out 2 Bullet Tuesday posts where we described how to build this project in deep details:

https://onion.io/2bt-reading-dht-sensor-data/
https://onion.io/2bt-dht-sensor-program/

**Comment by bhontz** [comment]
Many thanks.
